//! Cross-project crawling: the demo set (shop → infra → monitoring cycle,
//! children, components) and the trigger edge cases.

mod support;

use std::sync::Arc;

use glpv_core::model::{NeedKind, PipelineKind, UnresolvedReason};
use glpv_core::resolve::ResolveOpts;
use glpv_core::scan::{ScanOutput, scan_entry};
use glpv_core::source::ProjectLocator;
use glpv_core::source::index::LocalIndex;
use glpv_core::source::{ProjectKey, ProjectSource, Sources, TreeRef};
use glpv_core::vars::Scenario;

fn scan(root: &std::path::Path, host: &str, entry: &str) -> ScanOutput {
    let index = Arc::new(LocalIndex::build(&[root.to_path_buf()], &[]));
    let sources = Sources {
        locator: Some(index.clone()),
        templates_key: ProjectKey::new("gitlab.com", "gitlab-org/gitlab"),
    };
    let project = index
        .lookup(&ProjectKey::new(host, entry))
        .expect("entry in index");
    let branch = project.default_branch().unwrap();
    let sha = project.resolve_ref(&branch).unwrap().unwrap();
    let opts = ResolveOpts {
        embed_sources: false,
        ..ResolveOpts::default()
    };
    scan_entry(
        &sources,
        project,
        TreeRef::Commit(sha),
        Some(branch),
        None,
        &Scenario::push_default(),
        &opts,
        vec![],
        Vec::new(),
    )
}

#[test]
fn demo_set_crawls_the_whole_flow() {
    let root = support::demo_root();
    let output = scan(&root, "gitlab.example.com", "pipelines-demo/shop");
    let g = &output.graph;

    let kind_of = |path: &str, config_contains: &str| {
        g.pipelines
            .iter()
            .find(|p| p.project.path.ends_with(path) && p.config_path.contains(config_contains))
            .unwrap_or_else(|| panic!("pipeline {path} {config_contains} missing"))
    };

    assert_eq!(g.pipelines.len(), 8);
    assert_eq!(kind_of("shop", ".gitlab-ci.yml").kind, PipelineKind::Root);
    assert_eq!(kind_of("shop", "deploy-review").kind, PipelineKind::Child);
    let grandchild = kind_of("shop", "smoke-suite");
    assert_eq!(grandchild.kind, PipelineKind::Child);
    assert_eq!(grandchild.depth, 2);
    assert_eq!(
        kind_of("infra", ".gitlab-ci.yml").kind,
        PipelineKind::MultiProject
    );
    assert_eq!(
        kind_of("monitoring", ".gitlab-ci.yml").kind,
        PipelineKind::MultiProject
    );
    assert_eq!(
        kind_of("analytics", ".gitlab-ci.yml").kind,
        PipelineKind::MultiProject
    );
    assert_eq!(
        kind_of("analytics", "generated by").kind,
        PipelineKind::DynamicChild
    );
    let unresolved = kind_of("$REGION-stack", "");
    assert_eq!(
        unresolved.unresolved.as_ref().unwrap().reason,
        UnresolvedReason::VariableInLocation
    );

    // monitoring's rollback trigger points back at infra: a cycle back-edge.
    let cycles: Vec<_> = g.trigger_edges.iter().filter(|e| e.cycle).collect();
    assert_eq!(cycles.len(), 1);
    assert!(cycles[0].from_job.0.ends_with("rollback-infra"));
    let infra_id = &kind_of("infra", ".gitlab-ci.yml").id;
    assert_eq!(&cycles[0].to_pipeline, infra_id);

    // The variable branch was resolved from the YAML variables.
    let analytics = kind_of("analytics", ".gitlab-ci.yml");
    assert_eq!(analytics.git_ref.as_deref(), Some("main"));

    // Cross-project include at a pinned ref (v2) and component via tag both
    // landed as include edges into ci-templates.
    let templated: Vec<_> = g
        .include_files
        .iter()
        .filter(|f| {
            f.project
                .as_ref()
                .is_some_and(|p| p.path.ends_with("ci-templates"))
        })
        .collect();
    assert!(
        templated.len() >= 3,
        "shop, infra and analytics all pull ci-templates"
    );

    // The shop build job inherited its image across projects.
    let shop = kind_of("shop", ".gitlab-ci.yml");
    let build = shop.jobs.iter().find(|j| j.name == "build").unwrap();
    assert_eq!(build.image.as_deref(), Some("rust:1.85-bookworm"));

    // ~latest component is unresolved with the catalog reason.
    assert!(g.include_files.iter().any(
        |f| matches!(&f.unresolved, Some(u) if u.reason == UnresolvedReason::ComponentNeedsCatalog)
    ));
}

#[test]
fn trigger_edge_cases() {
    let root = support::fixture_root(&["trig-x", "trig-y"]);
    let output = scan(&root, "fixtures.local", "fx/trig-x");
    let g = &output.graph;
    let codes: Vec<&str> = g.diagnostics.iter().map(|d| d.code.as_str()).collect();

    // include cycle inc-a ↔ inc-b
    assert!(codes.contains(&"include.cycle"));
    // 4 child config files
    assert!(codes.contains(&"trigger.too-many-includes"));
    // parent → c1 → c2 → c1 would be depth 3
    assert!(codes.contains(&"trigger.child-depth"));
    assert!(g.pipelines.iter().any(|p| matches!(
        &p.unresolved,
        Some(u) if u.reason == UnresolvedReason::ChildDepthExceeded
    )));

    // string-form trigger reached trig-y
    assert!(
        g.pipelines
            .iter()
            .any(|p| p.project.path == "fx/trig-y" && p.kind == PipelineKind::MultiProject)
    );

    // needs:project is an artifact edge, not a trigger
    let tx = g
        .pipelines
        .iter()
        .find(|p| p.kind == PipelineKind::Root)
        .unwrap();
    let gen_job = tx.jobs.iter().find(|j| j.name == "gen").unwrap();
    assert_eq!(gen_job.needs[0].kind, NeedKind::CrossProjectArtifact);
    assert_eq!(gen_job.needs[0].project.as_deref(), Some("fx/trig-y"));
}

#[test]
fn scan_all_discovers_detached_and_reorders() {
    let root = support::demo_root();
    let index = Arc::new(LocalIndex::build(&[root], &[]));
    let sources = Sources {
        locator: Some(index.clone()),
        templates_key: ProjectKey::new("gitlab.com", "gitlab-org/gitlab"),
    };
    let projects: Vec<Arc<dyn ProjectSource>> = index
        .all()
        .iter()
        .filter_map(|m| index.lookup(&m.key))
        .map(|p| p as Arc<dyn ProjectSource>)
        .collect();
    let opts = ResolveOpts {
        embed_sources: false,
        ..ResolveOpts::default()
    };
    let output = glpv_core::scan::scan_all(
        &sources,
        projects,
        &Scenario::push_default(),
        &opts,
        vec![],
        Vec::new(),
    );
    let g = &output.graph;

    // The 8 pipelines reachable from shop plus the detached nightly cleanup.
    assert_eq!(g.pipelines.len(), 9);
    let nightly = g
        .pipelines
        .iter()
        .find(|p| p.config_path == "ops/nightly-cleanup.yml")
        .expect("detached pipeline discovered");
    assert_eq!(nightly.kind, PipelineKind::Detached);
    assert_eq!(nightly.depth, 0);
    // Its schedule-only job evaluates as skipped under the default push scenario.
    let prune = nightly
        .jobs
        .iter()
        .find(|j| j.name == "prune-registry")
        .unwrap();
    assert_eq!(
        prune.evaluations[0].outcome,
        glpv_core::model::Outcome::Skipped
    );

    // The non-CI yaml was not picked up.
    assert!(
        !g.pipelines
            .iter()
            .any(|p| p.config_path.contains("settings"))
    );
    assert!(!g.sources.iter().any(|s| s.path.contains("settings")));

    // Projects crawled as roots but triggered by shop were re-classified with
    // parent-chain depths (shop d0 → infra d1 → monitoring d2).
    let infra = g
        .pipelines
        .iter()
        .find(|p| p.project.path.ends_with("infra"))
        .unwrap();
    assert_eq!(infra.kind, PipelineKind::MultiProject);
    assert_eq!(infra.depth, 1);
    assert!(infra.parent.is_some());
    let monitoring = g
        .pipelines
        .iter()
        .find(|p| p.project.path.ends_with("monitoring"))
        .unwrap();
    assert_eq!(monitoring.depth, 2);
    assert!(g.diagnostics.iter().any(|d| d.code == "discover.detached"));
}
